### ISSUE TITLE
Failure when executing AddIPPoolInSdaVirtualNetwork with `dnacenter_sda_virtual_network_ip_pool`

### ISSUE THREAD

**Issue by artur-tekieli** [cisco-en-programmability/terraform-provider-dnacenter#174]
**Prerequisites**
* [x] Do you have the latest Terraform provider version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
`terraform apply` of 'dnacenter_sda_virtual_network_ip_pool'  fails with **Failure when executing AddIPPoolInSdaVirtualNetwork**, 
after waiting for a few minutes and running again `terraform apply` it works.
see below debugs:
[first_run.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11439330/first_run.txt)
[second_run.txt](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/files/11439332/second_run.txt)

**Expected behavior**
It should work with one run of `terraform apply`

**Environment (please complete the following information):**
* Cisco DNA Center version and patch:  2.3.3.7
* Terraform version: 1.4.6
* Cisco DNA Center provider version: 1.1.4-beta
* OS Version: MacOS 13.3.1

**Comment by artur-tekieli** [comment]
Also tested with 1.1.6-beta and have the same issue.

**Comment by wastorga** [comment]
Hi @artur-tekieli

On DNAC version 2.3.5.3 +, the execution status changed from 

1. FAILURE to failed
2. IN_PROGRESS to pending 

We still use the previous status values, so we did not wait correctly for the execution to change.

I am currently working on a fix.

**Comment by wastorga** [comment]
The new Terraform provider for dnacenter is up, v1.1.10-beta.

Please, try again with the new version.

**Comment by wastorga** [comment]
Your Cisco DNA Center version is 2.3.3.7; according to our Compatibility Matrix your "dnacenter" provider version should be 1.0.19-beta.

I recommend, however that you upgrade DNA Center to a newer release, at least for the following reasons.

- There have been multiple improvements and fixes in DNA Center APIs
- Our Terraform provider "dnacenter" development effort moves towards supporting the last DNA Center versions on the Compatibility Matrix (for now, 2.3.5.3) rather than those below.

**Comment by fmunozmiranda** [comment]
@artur-tekieli , update us if it works now, or ticket is going to be closed in next 24 hours due inactivity.
