### ISSUE TITLE
Updates on `dnacenter_sda_virtual_network_ip_pool` resource says "Apply complete" but no change on dnac

### ISSUE THREAD

**Issue by edudppaz** [cisco-en-programmability/terraform-provider-dnacenter#210]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest Terraform provider version?
* [X] Review the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
When doing changes to any resource provisioned via `dnacenter_sda_virtual_network_ip_pool`, a terraform plan shows that a change is being made and a terraform apply says "Apply complete", but there is no actual change on DNAC.

**Expected behavior**
Changes to the IP Pool on terraform should be reflected on DNA Center. For example. enabling/disabling flooding, enabling/disabling wireless, and so on.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center version and patch: 2.3.5.4-70852
* Terraform version: 1.5.6
* Cisco DNA Center provider version: 1.1.16-beta
* OS Version: Ubuntu

**Additional context**
Same is happeing with other resources (for example, `dnacenter_business_sda_hostonboarding_ssid_ippool` so this might be a client sdk issue that affects several resources.

**Comment by fmunozmiranda** [comment]
Hi @edudppaz , problem is that there's no API for PUT to this endpoint, our provider depends on the API operations, so that's why resource is not updated in DNAC.

Doc about this endpoint:
![image](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/assets/93611708/106745b3-2106-4e62-9ad4-504714704823)

**Comment by edudppaz** [comment]
Hi @fmunozmiranda , then the resource should destroy and recreate.  

I dont know the internals about terraform providers, but the ACI provider has a few resources that cannot be updated (as the object itself cannot be modified), so when the operator makes a change, there is a "forced destroy" being informed by the plan, so even if there is no PUT, its totally possible via terraform.

**Comment by zapodeanu** [comment]
@edudppaz We will not be able to support methods for which we do not have an API endpoint in Catalyst Center. It would be hard to know if the REST API does not exist because the operation is not supported in Catalyst Center or it is on the roadmap. I could see where we would run in provider backward compatibility issues  when the API may be released in the future and the current "workaround" will not match the new API endpoint.

**Comment by mschedrin** [comment]
According to the [compatibility matrix](https://github.com/cisco-en-programmability/terraform-provider-dnacenter/tree/main#compatibility-matrix), the provider seems to be made for specific Catalyst Center versions. I think it makes sense to support built-in Terraform methods by tapping into the API methods that match the version supported by the Terraform provider. When there's a new Catalyst Center version out, the provider release can be aligned to utilize new API endpoints. Doing it this way lets Catalyst Center users to use as much programmatic functions of the product as possible.

**Comment by edudppaz** [comment]
As discussed, the provider wont support "changes" via destroy if there is no PUT available.
